# ----
# Site
repository: srust/dev

# Personal info
name: Stephen Rust
title: Principal Architect
email: srust@srust.dev

# Social links
twitter_username: srust
github_username:  srust
linkedin_username: srust-dev

title: srust
url: "https://srust.dev/"
baseurl:
google_analytics_key:
disqus_shortname:
newsletter_action:

darkmode: false

# About Section
about_profile_image: images/srust.png

# Projects Section
projects_title: Skills

# Values for the jekyll-seo-tag gem (https://github.com/jekyll/jekyll-seo-tag)
logo: /siteicon.png
description: srust.dev
author:
  name: Stephen Rust
  email: srust@srust.dev
  twitter: srust
social:
  name: Base Template
  links:
    - https://github.com/CloudCannon/base-jekyll-template

# -----
# Build

timezone: Etc/UTC

permalink: /:categories/:title/

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-extract-element
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-archives

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENCE

collections:
  sets:

jekyll-archives:
  enabled: ['categories']

defaults:
  -
    scope:
      path: "index.html"
    values:
      layout: "main"
  -
    scope:
      path: "kb"
    values:
      body_class: "show_hero_search"
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      type: "sets"
    values:
      _hide_content: true

# -----------
# CloudCannon

social_icons:
  - Facebook
  - Google Plus
  - Instagram
  - LinkedIn
  - Pinterest
  - Tumblr
  - Twitter
  - YouTube
  - Email
  - RSS
  - Github

types:
  - Main
  - Document
  - Video

_comments:
