# ----
# Site
repository: srust/dev

# Personal info
name: Stephen Rust
title: Senior Member of Technical Staff
email: srust.dev@srust.org

# Social links
twitter_username: srust
github_username:  srust

title: srust
url: "https://srust.dev/"
baseurl:
google_analytics_key:
disqus_shortname:
newsletter_action:

darkmode: false

# About Section
about_profile_image: images/srust.png
about_content: | # this will include new lines to allow paragraphs
  I’m a developer and problem solver with 20 years of experience shipping production software, specializing in storage I/O technologies, distributed applications, systems programming, operating systems and virtualization.

# Values for the jekyll-seo-tag gem (https://github.com/jekyll/jekyll-seo-tag)
logo: /siteicon.png
description: Knowledge base template for Jekyll.
author:
  name:
  email:
  twitter: # twitter username without the @ symbol
social:
  name: Base Template
  links:
    - https://github.com/CloudCannon/base-jekyll-template

# -----
# Build

timezone: Etc/UTC

permalink: /:categories/:title/

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-extract-element
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-archives

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENCE

collections:
  sets:

jekyll-archives:
  enabled: ['categories']

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      type: "sets"
    values:
      _hide_content: true
  -
    scope:
      path: "index.html"
    values:
      layout: "main"
  -
    scope:
      path: "details.html"
    values:
      layout: "main"
  -
    scope:
      path: "kb.html"
    values:
      body_class: "show_hero_search"

# -----------
# CloudCannon

social_icons:
  - Facebook
  - Google Plus
  - Instagram
  - LinkedIn
  - Pinterest
  - Tumblr
  - Twitter
  - YouTube
  - Email
  - RSS
  - Github

types:
  - Main
  - Document
  - Video

_comments:
